ANNEX_A_CONTROLS = [
    # 5 - Organisatoriske kontroller
    {"ref": "5.1", "name": "Retningslinjer for informasjonssikkerhet"},
    {"ref": "5.2", "name": "Roller og ansvar for informasjonssikkerhet"},
    {"ref": "5.3", "name": "Ansvarsdeling"},
    {"ref": "5.4", "name": "Ledelsesansvar"},
    {"ref": "5.5", "name": "Kontakt med myndigheter"},
    {"ref": "5.6", "name": "Kontakt med spesielle interessegrupper"},
    {"ref": "5.7", "name": "Trusseletterretning"},
    {"ref": "5.8", "name": "Informasjonssikkerhet i prosjektledelse"},
    {"ref": "5.9", "name": "Inventar over informasjon og andre tilhørende eiendeler"},
    {"ref": "5.10", "name": "Akseptabel bruk av informasjon og andre tilhørende eiendeler"},
    {"ref": "5.11", "name": "Tilbakelevering av eiendeler"},
    {"ref": "5.12", "name": "Klassifisering av informasjon"},
    {"ref": "5.13", "name": "Merking av informasjon"},
    {"ref": "5.14", "name": "Informasjonsoverføring"},
    {"ref": "5.15", "name": "Tilgangskontroll"},
    {"ref": "5.16", "name": "Identitetshåndtering"},
    {"ref": "5.17", "name": "Autentiseringsinformasjon"},
    {"ref": "5.18", "name": "Tilgangsrettigheter"},
    {"ref": "5.19", "name": "Informasjonssikkerhet i leverandørforhold"},
    {"ref": "5.20", "name": "Håndtering av informasjonssikkerhet i leverandøravtaler"},
    {"ref": "5.21", "name": "Håndtering av informasjonssikkerhet i IKT-leverandørkjeden"},
    {"ref": "5.22", "name": "Overvåking, gjennomgang og endringshåndtering av leverandørtjenester"},
    {"ref": "5.23", "name": "Informasjonssikkerhet ved bruk av skytjenester"},
    {"ref": "5.24", "name": "Planlegging og forberedelse av hendelseshåndtering"},
    {"ref": "5.25", "name": "Vurdering og beslutning om informasjonssikkerhetshendelser"},
    {"ref": "5.26", "name": "Respons på informasjonssikkerhetshendelser"},
    {"ref": "5.27", "name": "Læring fra informasjonssikkerhetshendelser"},
    {"ref": "5.28", "name": "Innsamling av bevis"},
    {"ref": "5.29", "name": "Informasjonssikkerhet under forstyrrelser"},
    {"ref": "5.30", "name": "IKT-beredskap for forretningskontinuitet"},
    {"ref": "5.31", "name": "Juridiske, regulatoriske og kontraktsmessige krav"},
    {"ref": "5.32", "name": "Immaterielle rettigheter"},
    {"ref": "5.33", "name": "Beskyttelse av registre"},
    {"ref": "5.34", "name": "Personvern og beskyttelse av personopplysninger"},
    {"ref": "5.35", "name": "Uavhengig gjennomgang av informasjonssikkerhet"},
    {"ref": "5.36", "name": "Etterlevelse av retningslinjer og standarder"},
    {"ref": "5.37", "name": "Dokumenterte driftsprosedyrer"},
    # 6 - Personkontroller
    {"ref": "6.1", "name": "Screening"},
    {"ref": "6.2", "name": "Ansettelsesvilkår"},
    {"ref": "6.3", "name": "Bevisstgjøring, opplæring og trening i informasjonssikkerhet"},
    {"ref": "6.4", "name": "Disiplinærprosess"},
    {"ref": "6.5", "name": "Ansvar etter opphør eller endring av ansettelse"},
    {"ref": "6.6", "name": "Konfidensialitets- og taushetserklæringer"},
    {"ref": "6.7", "name": "Fjernarbeid"},
    {"ref": "6.8", "name": "Rapportering av hendelser innen informasjonssikkerhet"},
    # 7 - Fysiske kontroller
    {"ref": "7.1", "name": "Fysiske sikkerhetsperimetre"},
    {"ref": "7.2", "name": "Fysisk adgang"},
    {"ref": "7.3", "name": "Sikring av kontorer, rom og fasiliteter"},
    {"ref": "7.4", "name": "Overvåking av fysisk sikkerhet"},
    {"ref": "7.5", "name": "Beskyttelse mot fysiske trusler og miljøtrusler"},
    {"ref": "7.6", "name": "Arbeid i sikrede områder"},
    {"ref": "7.7", "name": "Ren skrivebordspolitikk og ren skjermpolitikk"},
    {"ref": "7.8", "name": "Plassering og beskyttelse av utstyr"},
    {"ref": "7.9", "name": "Sikkerhet for eiendeler utenfor lokaler"},
    {"ref": "7.10", "name": "Lagringsmedier"},
    {"ref": "7.11", "name": "Støtteverktøy"},
    {"ref": "7.12", "name": "Kablingssikkerhet"},
    {"ref": "7.13", "name": "Vedlikehold av utstyr"},
    {"ref": "7.14", "name": "Sikker avhending eller gjenbruk av utstyr"},
    # 8 - Teknologiske kontroller
    {"ref": "8.1", "name": "Brukerendepunktsenheter"},
    {"ref": "8.2", "name": "Privilegerte tilgangsrettigheter"},
    {"ref": "8.3", "name": "Begrensning av informasjonstilgang"},
    {"ref": "8.4", "name": "Tilgang til kildekode"},
    {"ref": "8.5", "name": "Sikker autentisering"},
    {"ref": "8.6", "name": "Kapasitetsstyring"},
    {"ref": "8.7", "name": "Beskyttelse mot skadevare"},
    {"ref": "8.8", "name": "Håndtering av tekniske sårbarheter"},
    {"ref": "8.9", "name": "Konfigurasjonsstyring"},
    {"ref": "8.10", "name": "Sletting av informasjon"},
    {"ref": "8.11", "name": "Datamaskering"},
    {"ref": "8.12", "name": "Forebygging av datalekkasje"},
    {"ref": "8.13", "name": "Sikkerhetskopiering av informasjon"},
    {"ref": "8.14", "name": "Redundans av informasjonsbehandlingsanlegg"},
    {"ref": "8.15", "name": "Logging"},
    {"ref": "8.16", "name": "Overvåkingsaktiviteter"},
    {"ref": "8.17", "name": "Klokkesynkronisering"},
    {"ref": "8.18", "name": "Bruk av privilegerte systemverktøy"},
    {"ref": "8.19", "name": "Installasjon av programvare på operative systemer"},
    {"ref": "8.20", "name": "Nettverkssikkerhet"},
    {"ref": "8.21", "name": "Sikkerhet i nettverkstjenester"},
    {"ref": "8.22", "name": "Segregering av nettverk"},
    {"ref": "8.23", "name": "Webfiltrering"},
    {"ref": "8.24", "name": "Bruk av kryptografi"},
    {"ref": "8.25", "name": "Sikker utviklingslivssyklus"},
    {"ref": "8.26", "name": "Krav til applikasjonssikkerhet"},
    {"ref": "8.27", "name": "Sikker systemarkitektur og tekniske prinsipper"},
    {"ref": "8.28", "name": "Sikker koding"},
    {"ref": "8.29", "name": "Sikkerhetstesting i utvikling og aksept"},
    {"ref": "8.30", "name": "Utkontraktert utvikling"},
    {"ref": "8.31", "name": "Separasjon av utviklings-, test- og produksjonsmiljøer"},
    {"ref": "8.32", "name": "Endringshåndtering"},
    {"ref": "8.33", "name": "Testinformasjon"},
    {"ref": "8.34", "name": "Beskyttelse av informasjonssystemer under revisjonstesting"},
]